### PR TITLE
Address D0154R1 comments from LWG

### PR DESCRIPTION
**Pull request by jfbastien**

### CODE REVIEW

**Comment by jfbastien** [comment]
@ogiroux please take a look.

@StephanTLavavej as you suggested?

**Comment by jfbastien** [comment]
@StephanTLavavej suggested that I use `cat` and `kitten` for `together`, but I've decided that lack of Standard [term of venery](https://en.wikipedia.org/wiki/List_of_English_terms_of_venery,_by_animal) for `cat` was too confusing: clowder, cluster, clutter, glaring, pounce, destruction. I'm going to assume this was a non-mandatory editorial suggestion.

**Comment by ogiroux** [comment]
I don't particularly like the forced humor injection here.

**Comment by ogiroux** [comment]
Apart is a different concept from not-the-same.

**Pull request merged**
